package lt.tacreports

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

/**
 * Every UI text in English and Lithuanian. Kept in code rather than platform resources so the
 * in-app language switch works the same on Android and iOS, without restarting a screen.
 */
class Strings(
    val bubble: String,
    val bubbleHelp: String,
    val overlayNeeded: String,
    val bubbleChannel: String,
    val bubbleNotification: String,
    val bubbleNotificationText: String,
    val bubbleStop: String,
    val bubbleOpen: String,
    val quickAccess: String,
    val quickAccessHelp: String,
    val templates: String,
    val fieldCount: (Int) -> String,
    val fill: String,
    val newTemplate: String,
    val newTemplateName: String,
    val importClipboard: String,
    val shareAll: String,
    val restoreExamples: String,
    val importNone: String,
    val imported: (Int) -> String,
    val language: String,
    val languageAuto: String,
    val mgrsPrecision: String,
    val dtgHelp: String,
    val editTemplate: String,
    val templateName: String,
    val share: String,
    val duplicate: String,
    val copySuffix: String,
    val delete: String,
    val deleteConfirm: String,
    val kindInput: String,
    val kindFixed: String,
    val kindHeader: String,
    val hintLabel: String,
    val hintSection: String,
    val hintFixed: String,
    val hintHint: String,
    val hintOptions: String,
    val remember: String,
    val addField: String,
    val addSection: String,
    val editorHelp: String,
    val pickTitle: String,
    val noTemplates: String,
    val draft: String,
    val manageTemplates: String,
    val clear: String,
    val preview: String,
    val edit: String,
    val copyReport: String,
    val copied: String,
    val noFix: String,
    val oldFix: (Int) -> String,
    val noLocationPermission: String,
)

val En = Strings(
    bubble = "Floating bubble",
    bubbleHelp = "A button over other apps. Tap it, pick a report, fill in the blanks and tap Copy: the text is ready to paste into any chat. Drag it to move it.",
    overlayNeeded = "Allow \"Display over other apps\" for TacReports, then come back.",
    bubbleChannel = "Floating bubble",
    bubbleNotification = "Report bubble is on",
    bubbleNotificationText = "Tap the bubble to fill in a report.",
    bubbleStop = "Stop",
    bubbleOpen = "Open reports",
    quickAccess = "Quick access",
    quickAccessHelp = "The Shortcuts app has a TacReports action \"New report\". Put it on the Action Button " +
        "(Settings › Action Button) or on Back Tap (Settings › Accessibility › Touch › Back Tap). " +
        "After Copy, switch back to the chat and paste.",
    templates = "Templates",
    fieldCount = { "$it fields to fill" },
    fill = "Fill",
    newTemplate = "+ New",
    newTemplateName = "New report",
    importClipboard = "Import",
    shareAll = "Share all",
    restoreExamples = "Restore examples",
    importNone = "No templates found. Copy a shared template text first.",
    imported = { "Imported $it templates" },
    language = "Language",
    languageAuto = "Phone",
    mgrsPrecision = "MGRS digits",
    dtgHelp = "DTG: DD HHMM Z MMM YY, e.g. 03 1825 C OCT 26. C = summer time, B = winter time.",
    editTemplate = "Template",
    templateName = "Name",
    share = "Share",
    duplicate = "Duplicate",
    copySuffix = "(copy)",
    delete = "Delete",
    deleteConfirm = "Sure?",
    kindInput = "Fill in",
    kindFixed = "Fixed",
    kindHeader = "Section",
    hintLabel = "Label, e.g. 1 Vieta",
    hintSection = "Section title (empty = end of section)",
    hintFixed = "Fixed text",
    hintHint = "Grey hint (optional)",
    hintOptions = "Options, one per line: CODE = text (optional)",
    remember = "Keep last value (e.g. Kam, Nuo)",
    addField = "+ Field",
    addSection = "+ Section",
    editorHelp = "Fill in: asked each time. Fixed: always printed, never asked. Section: a title printed only when a field below it has a value. Empty fields are left out of the report.",
    pickTitle = "Report",
    noTemplates = "No templates yet.",
    draft = "draft",
    manageTemplates = "Manage templates",
    clear = "Clear",
    preview = "Preview",
    edit = "Edit",
    copyReport = "Copy report",
    copied = "Copied, ready to paste",
    noFix = "No GPS fix. Go outside or wait a moment.",
    oldFix = { "Position is $it min old" },
    noLocationPermission = "Location permission is needed for MGRS",
)

val Lt = Strings(
    bubble = "Plaukiojantis mygtukas",
    bubbleHelp = "Mygtukas virš kitų programų. Paspauskite, pasirinkite raportą, užpildykite tuščius laukus ir spauskite „Kopijuoti“: tekstą galima įklijuoti į bet kurį pokalbį. Mygtuką galima tempti.",
    overlayNeeded = "Leiskite TacReports „Rodyti virš kitų programų“ ir grįžkite.",
    bubbleChannel = "Plaukiojantis mygtukas",
    bubbleNotification = "Raportų mygtukas įjungtas",
    bubbleNotificationText = "Paspauskite mygtuką raportui užpildyti.",
    bubbleStop = "Išjungti",
    bubbleOpen = "Atidaryti raportus",
    quickAccess = "Greitas atidarymas",
    quickAccessHelp = "Programoje „Shortcuts“ yra TacReports veiksmas „New report“. Priskirkite jį veiksmo mygtukui " +
        "(Nustatymai › Action Button) arba „Back Tap“ (Nustatymai › Prieinamumas › Lietimas › Back Tap). " +
        "Nukopijavę grįžkite į pokalbį ir įklijuokite.",
    templates = "Šablonai",
    fieldCount = { "Pildomų laukų: $it" },
    fill = "Pildyti",
    newTemplate = "+ Naujas",
    newTemplateName = "Naujas raportas",
    importClipboard = "Importuoti",
    shareAll = "Dalintis visais",
    restoreExamples = "Grąžinti pavyzdžius",
    importNone = "Šablonų nerasta. Pirmiau nukopijuokite atsiųstą šablono tekstą.",
    imported = { "Importuota šablonų: $it" },
    language = "Kalba",
    languageAuto = "Telefono",
    mgrsPrecision = "MGRS skaitmenys",
    dtgHelp = "DTG: DD HHMM Z MMM YY, pvz. 03 1825 C OCT 26. C – vasaros laikas, B – žiemos laikas.",
    editTemplate = "Šablonas",
    templateName = "Pavadinimas",
    share = "Dalintis",
    duplicate = "Kopija",
    copySuffix = "(kopija)",
    delete = "Trinti",
    deleteConfirm = "Tikrai?",
    kindInput = "Pildomas",
    kindFixed = "Pastovus",
    kindHeader = "Skyrius",
    hintLabel = "Pavadinimas, pvz. 1 Vieta",
    hintSection = "Skyriaus pavadinimas (tuščias = skyriaus pabaiga)",
    hintFixed = "Pastovus tekstas",
    hintHint = "Pilka užuomina (nebūtina)",
    hintOptions = "Pasirinkimai, po vieną eilutėje: KODAS = tekstas (nebūtina)",
    remember = "Prisiminti paskutinę reikšmę (pvz. Kam, Nuo)",
    addField = "+ Laukas",
    addSection = "+ Skyrius",
    editorHelp = "Pildomas: klausiama kiekvieną kartą. Pastovus: visada įrašomas, neklausiama. Skyrius: pavadinimas įrašomas tik tada, kai po juo yra užpildytas laukas. Tušti laukai į raportą neįtraukiami.",
    pickTitle = "Raportas",
    noTemplates = "Šablonų dar nėra.",
    draft = "juodraštis",
    manageTemplates = "Tvarkyti šablonus",
    clear = "Išvalyti",
    preview = "Peržiūra",
    edit = "Pildyti",
    copyReport = "Kopijuoti",
    copied = "Nukopijuota, galima įklijuoti",
    noFix = "Nėra GPS. Išeikite į lauką arba palaukite.",
    oldFix = { "Padėtis prieš $it min." },
    noLocationPermission = "MGRS reikia vietos leidimo",
)

fun stringsFor(language: String?): Strings = if ((language ?: systemLanguage()) == "lt") Lt else En

/** Texts for code outside the UI (notifications, toasts). */
fun currentStrings(): Strings = stringsFor(Prefs.language.value)

val LocalStrings = staticCompositionLocalOf { En }

@Composable
fun strings(): Strings = LocalStrings.current
